##### Problem statement: 

Given a bank customer, build a neural network-based classifier that can determine whether
they will leave or not in the next 6 months.
Dataset Description: The case study is from an open-source dataset from Kaggle.
The dataset contains 10,000 sample points with 14 distinct features such as
CustomerId, CreditScore, Geography, Gender, Age, Tenure, Balance, etc.
Link to the Kaggle project:
https://www.kaggle.com/barelydedicated/bank-customer-churn-modeling
Perform following steps:
1. Read the dataset.
2. Distinguish the feature and target set and divide the data set into training and test sets.
3. Normalize the train and test data.
4. Initialize and build the model. Identify the points of improvement and implement the same.
5. Print the accuracy score and confusion matrix (5 points).

##### NOTE: If you face problems on jupyter notebook try running this code on google collab.

## Read the dataset

In [2]:
import pandas as pd

df= pd.read_csv('/content/Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## Distinguish the feature and target set and divide the data set into training and test sets

In [3]:
cols= df.columns
cols

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [4]:
x= df[['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']]
y= df['Exited']

In [5]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest= train_test_split(x,y, test_size=0.2, random_state=42)

## Normalize the train and test data

In [6]:
from sklearn.preprocessing import MinMaxScaler

std= MinMaxScaler()
xtrain= std.fit_transform(xtrain)
xtest= std.transform(xtest)

## Initialize and build the model

In [7]:
import tensorflow as tf
from tensorflow import keras

model= keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(xtrain.shape[1],)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                576

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2689 (10.50 KB)
Trainable params: 2689 (10.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [8]:
model.fit(xtrain, ytrain, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
200/200 [==============================] - 2s 3ms/step - loss: 0.5150 - accuracy: 0.7702 - val_loss: 0.4629 - val_accuracy: 0.7994
Epoch 2/10
200/200 [==============================] - 0s 2ms/step - loss: 0.4601 - accuracy: 0.8070 - val_loss: 0.4309 - val_accuracy: 0.8238
Epoch 3/10
200/200 [==============================] - 0s 2ms/step - loss: 0.4379 - accuracy: 0.8155 - val_loss: 0.4142 - val_accuracy: 0.8250
Epoch 4/10
200/200 [==============================] - 0s 2ms/step - loss: 0.4204 - accuracy: 0.8258 - val_loss: 0.3991 - val_accuracy: 0.8375
Epoch 5/10
200/200 [==============================] - 1s 3ms/step - loss: 0.4055 - accuracy: 0.8281 - val_loss: 0.3826 - val_accuracy: 0.8431
Epoch 6/10
200/200 [==============================] - 1s 4ms/step - loss: 0.3879 - accuracy: 0.8428 - val_loss: 0.3782 - val_accuracy: 0.8431
Epoch 7/10
200/200 [==============================] - 1s 4ms/step - loss: 0.3757 - accuracy: 0.8466 - val_loss: 0.3675 - val_accuracy: 0.8487
Epoch 8/10
200/200 [==============================] - 1s 4ms/step - loss: 0.3712 - accuracy: 0.8491 - val_loss: 0.3836 - val_accuracy: 0.8344
Epoch 9/10
200/200 [==============================] - 1s 6ms/step - loss: 0.3658 - accuracy: 0.8512 - val_loss: 0.3594 - val_accuracy: 0.8512
Epoch 10/10
200/200 [==============================] - 1s 3ms/step - loss: 0.3629 - accuracy: 0.8542 - val_loss: 0.3573 - val_accuracy: 0.8506

In [10]:
ypred= (model.predict(xtest)>0.5)

63/63 [==============================] - 0s 1ms/step

## Print the accuracy score and confusion matrix

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [12]:
cm= confusion_matrix(ytest, ypred)
cm

array([[1563,   44],
       [ 248,  145]])

In [13]:
accuracy= accuracy_score(ytest, ypred)
print(accuracy)

0.854